
#include "wxinc.h"
#include <wx/xrc/xmlres.h>
#include "mainwindow.h"

#include "common/log.h"

#if defined(__GNUC__)
#  define __cdecl __attribute__((cdecl))
#endif

extern void InitXmlResource(); // Autogenerated in resource.cpp

namespace
{
    class Application : public wxApp
    {
    public:
        virtual bool OnInit()
        {
            Log::Init("ikamap.log");

            wxXmlResource::Get()->InitAllHandlers();
#if 0 && defined(_DEBUG) // doesn't work for some reason. :(
            wxXmlResource::Get()->Load("resource.xrc");
#else
            ::InitXmlResource();
#endif

            MainWindow* mainwnd = new MainWindow(wxDefaultPosition, wxSize(750,500));
            mainwnd->Show(true);

            if (argc > 1)
                mainwnd->LoadMap(argv[1]);

            SetTopWindow(mainwnd);
            return TRUE;
        }
    };
}

IMPLEMENT_APP(Application)

// HACK.  This shouldn't be needed in release mode. -_-
#ifndef _DEBUG
void __cdecl wxAssert(int, char const*, int, char const*, char const*)
{
    exit(-1);
}
#endif
