Import('*')

ikamap = ikaMap_env.Program('ikamap',
    source = Split('''
        brush.cpp
        brushstate.cpp
        command.cpp
        copypastestate.cpp
        editstate.cpp
        entitydlg.cpp
        entitystate.cpp
        exporttilesdlg.cpp
        ikamap.cpp
        imagebank.cpp
        importtilesdlg.cpp
        layerdlg.cpp
        layerlist.cpp
        mainwindow.cpp
        mapdlg.cpp
        mapview.cpp
        newmapdlg.cpp
        obstructionstate.cpp
        resource.cpp
        script.cpp
        scriptdlg.cpp
        scriptengine.cpp
        scriptstate.cpp
        settilestate.cpp
        spriteset.cpp
        tileanimdlg.cpp
        tileset.cpp
        tilesetview.cpp
        togglebitmapbutton.cpp
        userdialog.cpp
        video.cpp
        zoneeditstate.cpp
        zonepropertiesdlg.cpp
        script/EditorObject.cpp
        script/ErrorObject.cpp
        script/MapObject.cpp
        script/ModuleFuncs.cpp
        ''')
    )

Return('ikamap')
