Import('*')

ika = env.Program('ika',
    source = Split('''
        animscript.cpp
        benchmark.cpp
        entity.cpp
        font.cpp
        FPSCounter.cpp
        input.cpp
        joystick.cpp
        keyboard.cpp
        main.cpp
        mouse.cpp
        script.cpp
        scriptobject.cpp
        sound.cpp
        sprite.cpp
        tileset.cpp
        timer.cpp
        script/CanvasObject.cpp
        script/ControlObject.cpp
        script/EntityObject.cpp
        script/ErrorObject.cpp
        script/FontObject.cpp
        script/ImageObject.cpp
        script/InputDeviceObject.cpp
        script/InputObject.cpp
        script/JoystickObject.cpp
        script/KeyboardObject.cpp
        script/MapObject.cpp
        script/ModuleFuncs.cpp
        script/MouseObject.cpp
        script/SoundObject.cpp
        script/VideoObject.cpp
        opengl/Driver.cpp
        opengl/Image.cpp
        soft32/Driver.cpp
        soft32/Image.cpp
        ''')
    )

Return('ika')
