Import('*')

common = env.StaticLibrary('common',
    source = Split('''
        aries.cpp
        base64.cpp
        Canvas.cpp
        chr.cpp
        compression.cpp
        configfile.cpp
        fileio.cpp
        fontfile.cpp
        log.cpp
        map.cpp
        utility.cpp
        rle.cpp
        vergemap.cpp
        vergepal.cpp
        vsp.cpp
        ''')
    )

Return('common')
